theme: jekyll-theme-minimal
title: 株式会社Kunimasu
description: Iot / Mobile / Web をワンストップで企画・開発するテックカンパニーです。 受託開発他、実機モバイルのCI（Continuous Integration）のプロダクトの開発・運営。
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
